name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: cd docker && docker build -t bertrandd/dinap-rel-notes .
      - name: Login to registry
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push to registry
        run: docker push bertrandd/dinap-rel-notes